### ISSUE TITLE
Missing white space after "Standards for Study" on row 485

### ISSUE THREAD

**Issue by dostiep** [lexjansen/define-xml-2.1-stylesheets#8]
A white space is missing at the end of the string 'Standards for Study' on row 485 in order to avoid for this string and the study name to be displayed improperly. 

The solution is simply to add a whitespace after the word "Study" as shown below:

  <xsl:variable name="term_STANDARDS_FOR_STUDY">
    <xsl:call-template name="lookupTerm"><xsl:with-param name="term" select="'Standards for Study '"/></xsl:call-template>
  </xsl:variable>

**Comment by lexjansen** [comment]
The issue is actually in the dictionary.xml file. There should not be a space:
  <entry term="Standards for Study ">
I will fix this.
