### ISSUE TITLE
Suggested update for displayItemGroupClass template

### ISSUE THREAD

**Issue by dostiep** [lexjansen/define-xml-2.1-stylesheets#9]
I added some code to display properly subclasses for nested or multi-level sub-class.

  <xsl:template name="displayItemGroupClass">
    
      <xsl:if test="@def:Class">
        <xsl:value-of select="@def:Class" />    
      </xsl:if>

    <xsl:if test="def:Class/@Name">
      
      <xsl:variable name="ClassName" select="def:Class/@Name"/>
        <xsl:value-of select="$ClassName" />
		<xsl:for-each select="def:Class/def:SubClass[(@ParentClass=$ClassName or not(@ParentClass)) and @Name]">
		  <xsl:variable name="SubClass" select="@Name"/>
          <ul class="SubClass">
			<li class="SubClass"><xsl:value-of select="$SubClass" /></li>
			<ul class="ParentClass">
        	    <xsl:for-each select="../def:SubClass[@ParentClass=$SubClass]">
			  <li class="ParentClass"><xsl:value-of select="@Name" /></li>        
		    </xsl:for-each>
            </ul>
          </ul>
		</xsl:for-each>
		
        
        
      </xsl:if>
  </xsl:template>

It was tested on:

            <def:Class Name="OCCURRENCE DATA STRUCTURE">
               <def:SubClass Name="ADVERSE EVENT" ParentClass="OCCURRENCE DATA STRUCTURE"/>
               <def:SubClass Name="XXXX" ParentClass="ADVERSE EVENT"/>
               <def:SubClass Name="YYYYY"/>
               <def:SubClass Name="ZZZZZ" ParentClass="ADVERSE EVENT"/>
            </def:Class>

and the output was rendered as expected:

![image](https://user-images.githubusercontent.com/111854855/224322541-a5c8189f-d482-4205-ac46-65e665384d1f.png)

**Comment by lexjansen** [comment]
Excellent! Thank you. I will add this.

**Comment by lexjansen** [comment]
Stylesheet updated.
